<def f='linux-4.18.y/arch/x86/mm/extable.c' l='45' ll='85' type='bool ex_handler_refcount(const struct exception_table_entry * fixup, struct pt_regs * regs, int trapnr)'/>
<dec f='linux-4.18.y/arch/x86/mm/extable.c' l='86' type='bool ex_handler_refcount(const struct exception_table_entry * , struct pt_regs * , int )'/>
<use f='linux-4.18.y/arch/x86/mm/extable.c' l='86' c='ex_handler_refcount'/>
<use f='linux-4.18.y/arch/x86/mm/extable.c' l='86' u='a'/>
<use f='linux-4.18.y/arch/x86/mm/extable.c' l='86' u='a'/>
<doc f='linux-4.18.y/arch/x86/mm/extable.c' l='41'>/*
 * Handler for UD0 exception following a failed test against the
 * result of a refcount inc/dec/add/sub.
 */</doc>
