<def f='linux-4.18.y/include/trace/events/ext4.h' l='2608' macro='1' type='void trace_ext4_error(struct super_block * sb, const char * function, unsigned int line)'/>
<use f='linux-4.18.y/fs/ext4/super.c' l='452' u='c' c='__ext4_error'/>
<use f='linux-4.18.y/fs/ext4/super.c' l='477' u='c' c='__ext4_error_inode'/>
<use f='linux-4.18.y/fs/ext4/super.c' l='513' u='c' c='__ext4_error_file'/>
<use f='linux-4.18.y/fs/ext4/super.c' l='726' u='c' c='__ext4_grp_locked_error'/>
