<def f='include/boost/throw_exception.hpp' l='58' type='void boost::throw_exception_assert_compatibility(const std::exception &amp; )'/>
