<def f='include/boost/exception/exception.hpp' l='212' ll='217' type='void boost::exception::exception()'/>
