<inh f='include/boost/exception/exception.hpp' l='397' c='_ZNK5boost16exception_detail10clone_base7rethrowEv'/>
<def f='include/boost/exception/exception.hpp' l='463' ll='467' type='void boost::exception_detail::clone_impl::rethrow() const'/>
