<def f='include/boost/exception/exception.hpp' l='207' ll='267'/>
<ovr f='include/boost/exception/exception.hpp' l='320' c='boost::exception_detail::error_info_injector'/>
<size>40</size>
<fun r='_ZN5boost9exceptionC1Ev'/>
<fun r='_ZN5boost9exceptionD1Ev'/>
<mbr r='boost::exception::data_' o='64' t='exception_detail::refcount_ptr&lt;exception_detail::error_info_container&gt;'/>
<mbr r='boost::exception::throw_function_' o='128' t='const char *'/>
<mbr r='boost::exception::throw_file_' o='192' t='const char *'/>
<mbr r='boost::exception::throw_line_' o='256' t='int'/>
<fun r='_ZN5boost9exceptionD1Ev'/>
