<def f='include/boost/exception/exception.hpp' l='27' ll='30' type='void boost::exception_detail::refcount_ptr::refcount_ptr&lt;T&gt;()'/>
<use f='include/boost/exception/exception.hpp' l='414' u='c' c='_ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_'/>
