<def f='include/boost/exception/exception.hpp' l='399' ll='402' type='void boost::exception_detail::clone_base::~clone_base()'/>
<ovr f='include/boost/exception/exception.hpp' l='451' c='_ZN5boost16exception_detail10clone_implD1Ev'/>
