<def f='include/boost/throw_exception.hpp' l='80' ll='92' macro='1' type='void boost::exception_detail::throw_exception_(const E &amp; x, const char * current_function, const char * file, int line)'/>
