<use f='include/boost/exception/exception.hpp' l='40' u='c' c='_ZN5boost16exception_detail12refcount_ptrC1ERKNS0_12refcount_ptrIT_EE'/>
<use f='include/boost/exception/exception.hpp' l='55' u='c' c='_ZN5boost16exception_detail12refcount_ptr5adoptEPT_'/>
<def f='include/boost/exception/exception.hpp' l='68' ll='73' type='void boost::exception_detail::refcount_ptr::add_ref()'/>
