<dec f='include/c++/4.8.2/exception' l='68' type='const char * std::exception::what() const'/>
<ovr f='include/c++/4.8.2/ext/concurrence.h' l='71' c='__gnu_cxx::__concurrence_lock_error::what'/>
<ovr f='include/c++/4.8.2/ext/concurrence.h' l='79' c='__gnu_cxx::__concurrence_unlock_error::what'/>
<ovr f='include/c++/4.8.2/ext/concurrence.h' l='87' c='__gnu_cxx::__concurrence_broadcast_error::what'/>
<ovr f='include/c++/4.8.2/ext/concurrence.h' l='95' c='__gnu_cxx::__concurrence_wait_error::what'/>
<ovr f='include/boost/smart_ptr/bad_weak_ptr.hpp' l='43' c='_ZNK5boost12bad_weak_ptr4whatEv'/>
<ovr f='vpp_1804/src/vpp-api/vapi/vapi.hpp' l='61' c='_ZNK4vapi27Unexpected_msg_id_exception4whatEv'/>
<ovr f='vpp_1804/src/vpp-api/vapi/vapi.hpp' l='70' c='_ZNK4vapi27Msg_not_available_exception4whatEv'/>
<doc f='include/c++/4.8.2/exception' l='66'>/** Returns a C-style character string describing the general cause
     *  of the current error.  */</doc>
