<inh f='include/c++/4.8.2/exception' l='68' c='_ZNKSt9exception4whatEv'/>
<def f='vpp_1804/src/vpp-api/vapi/vapi.hpp' l='61' ll='64' type='const char * vapi::Unexpected_msg_id_exception::what() const'/>
