<def f='include/c++/4.8.2/future' l='1000' ll='1006' type='void std::promise::set_exception(std::__exception_ptr::exception_ptr __p)'/>
