<def f='include/c++/4.8.2/future' l='1172' ll='1178' type='void std::promise&lt;void&gt;::set_exception(std::__exception_ptr::exception_ptr __p)'/>
