<def f='include/boost/exception/exception.hpp' l='22' ll='81'/>
<fun r='_ZN5boost16exception_detail12refcount_ptrC1Ev'/>
<fun r='_ZN5boost16exception_detail12refcount_ptrD1Ev'/>
<fun r='_ZN5boost16exception_detail12refcount_ptrC1ERKNS0_12refcount_ptrIT_EE'/>
<fun r='_ZN5boost16exception_detail12refcount_ptraSERKNS0_12refcount_ptrIT_EE'/>
<fun r='_ZN5boost16exception_detail12refcount_ptr5adoptEPT_'/>
<fun r='_ZNK5boost16exception_detail12refcount_ptr3getEv'/>
<mbr r='boost::exception_detail::refcount_ptr::px_' t='T *'/>
<fun r='_ZN5boost16exception_detail12refcount_ptr7add_refEv'/>
<fun r='_ZN5boost16exception_detail12refcount_ptr7releaseEv'/>
