<dec f='dpdk_18.05/lib/librte_ethdev/rte_flow.h' l='1930' type='const void *'/>
<offset>64</offset>
<doc f='dpdk_18.05/lib/librte_ethdev/rte_flow.h' l='1930'>/**&lt; Object responsible for the error. */</doc>
<use f='dpdk_18.05/app/test-pmd/config.c' l='1342' u='r' c='port_flow_complain'/>
<use f='dpdk_18.05/app/test-pmd/config.c' l='1343' u='r' c='port_flow_complain'/>
<use f='dpdk_18.05/drivers/net/failsafe/failsafe_ether.c' l='43' u='r' c='fs_flow_complain'/>
<use f='dpdk_18.05/drivers/net/failsafe/failsafe_ether.c' l='44' u='r' c='fs_flow_complain'/>
<use f='dpdk_18.05/lib/librte_ethdev/rte_flow.c' l='282' u='w' c='rte_flow_error_set'/>
<dec f='vpp_1804/build-root/build-vpp_debug-native/dpdk/dpdk-stable-18.02.1/lib/librte_ether/rte_flow.h' l='1205' type='const void *'/>
<offset>64</offset>
<doc f='vpp_1804/build-root/build-vpp_debug-native/dpdk/dpdk-stable-18.02.1/lib/librte_ether/rte_flow.h' l='1205'>/**&lt; Object responsible for the error. */</doc>
<use f='vpp_1804/build-root/build-vpp_debug-native/dpdk/dpdk-stable-18.02.1/app/test-pmd/config.c' l='1188' u='r' c='port_flow_complain'/>
<use f='vpp_1804/build-root/build-vpp_debug-native/dpdk/dpdk-stable-18.02.1/app/test-pmd/config.c' l='1189' u='r' c='port_flow_complain'/>
<use f='vpp_1804/build-root/build-vpp_debug-native/dpdk/dpdk-stable-18.02.1/drivers/net/failsafe/failsafe_ether.c' l='43' u='r' c='fs_flow_complain'/>
<use f='vpp_1804/build-root/build-vpp_debug-native/dpdk/dpdk-stable-18.02.1/drivers/net/failsafe/failsafe_ether.c' l='44' u='r' c='fs_flow_complain'/>
<use f='vpp_1804/build-root/build-vpp_debug-native/dpdk/dpdk-stable-18.02.1/lib/librte_ether/rte_flow.c' l='250' u='w' c='rte_flow_error_set'/>
